name: FlipStore
version: '${project.version}'
main: cn.myrealm.flipstore.FlipStore
api-version: 1.13
authors: [ ManyouTeam ]
softdepend:
  - ProtocolLib
commands:
  flipstore:
    aliases:
      - fs
    description: Base command